(deftheme RyanTheme
  "Created 2016-12-14.")

(custom-theme-set-variables
 'RyanTheme
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-map [default default default italic underline success warning error nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil (foreground-color . "black") (foreground-color . "#d55e00") (foreground-color . "#009e73") (foreground-color . "#f8ec59") (foreground-color . "#0072b2") (foreground-color . "#cc79a7") (foreground-color . "#56b4e9") (foreground-color . "white") nil nil (background-color . "black") (background-color . "#d55e00") (background-color . "#009e73") (background-color . "#f8ec59") (background-color . "#0072b2") (background-color . "#cc79a7") (background-color . "#56b4e9") (background-color . "white") nil nil])
 '(ansi-color-names-vector ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(bind-key-describe-special-forms t)
 '(async-bytecomp-allowed-packages (quote (quote (async helm helm-core helm-ls-git helm-ls-hg magit all))))
 '(auth-source-protocols (quote (quote ((imap "imap" "imaps" "143" "993" "995") (pop3 "pop3" "pop" "pop3s" "110" "995" "993") (ssh "ssh" "22") (sftp "sftp" "115") (smtp "smtp" "25" "587")))))
 '(gnus-logo-colors (quote (quote ("#528d8d" "#c0c0c0"))))
 '(diary-entry-marker (quote (quote font-lock-variable-name-face)))
 '(company-auto-complete (quote (quote (quote company-explicit-action-p)))))

(custom-theme-set-faces
 'RyanTheme
 '(elfeed-search-title-face ((t (:foreground "light blue" :height 1.0))))
 '(org-agenda-column-dateline ((t (:height 1.0))))
 '(alert-low-face ((t (:background "blue" :foreground "secondaryLabelColor" :height 1.0))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#4e9a06"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#a40000"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#ce5c00"))))
 '(default ((t (:background "#2e3436" :foreground "#eeeeec" :family "Consolas"))))
 '(elfeed-search-title-face ((t (:foreground "light blue" :height 1.0))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff4b4b"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(ffap ((t (:inherit highlight :foreground "black" :height 1.0))))
 '(fringe ((((class color) (min-colors 89)) (:background "#212526"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#2e3436" :background "#edd400"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#eeeeec" :background "#ce5c00"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#8f5902"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#729fcf"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#3465a4"))))
 '(markdown-highlight-face ((t (:stipple nil :background "blue" :foreground "black" :height 1.0))))
 '(menu ((t (:background "gray30" :foreground "snow"))))
 '(mode-line ((t (:background "#d3d7cf" :foreground "steel blue" :family "DejaVu Sans"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "#555753" :foreground "#eeeeec"))))
 '(region ((((class color) (min-colors 89)) (:background "#555753"))))
 '(restclient-method-face ((t (:inherit font-lock-keyword-face :height 1.0))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#204a87"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#a40000"))))
 '(variable-pitch ((t (:height 1.0 :family "Consolas"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e090d7"))))
 '(font-lock-comment-face ((t (:foreground "peach puff" :slant italic :height 1.0 :family "Consolas"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e9b2e3"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#fce94f"))))
 '(font-lock-keyword-face ((t (:foreground "light sea green" :weight bold :height 1.0 :family "Consolas"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#e9b96e"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#8cc4ff"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#e090d7"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#e090d7"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#e9b2e3"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#fcaf3e"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#c4a000"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#729fcf"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#c17d11"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#8ae234"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#edd400"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#e090d7"))))
 '(org-agenda-column-dateline ((t (:height 1.0))))
 '(org-agenda-filter-category ((t (:height 1.0 :inherit mode-line))))
 '(org-block ((t (:foreground "#eeeeec" :background "light steel blue" :box nil))))
 '(org-block-begin-line ((t (:foreground "#eeeeec" :background "#204a87"))))
 '(org-block-end-line ((t (:foreground "#eeeeec" :background "#204a87"))))
 '(org-checkbox ((t (:foreground "#000000" :background "#93a1a1" :box (:line-width -3 :color "#93a1a1" :style "released-button")))))
 '(org-column ((t (:strike-through nil :underline nil :slant normal :weight normal :height 1.0 :family "Consolas"))))
 '(org-default ((t (:family "Consolas" :height 1.0 :box nil :inherit default))))
 '(org-document-title ((t (:inherit org-level-1 :family "Lucida Grande" :height 1.2 :underline nil :box nil :foreground "gold" :inherit org-level-1))))
 '(org-done ((t (:strike-through t))))
 '(org-footnote ((t (:foreground "light steel blue" :family "Consolas"))))
 '(org-habit-alert-face ((t (:background "red" :height 1.0))))
 '(org-headline-done ((t (:strike-through t))))
 '(org-level-1 ((t (:inherit default :foreground "#eeeeec" :font "Consolas"))))
 '(org-level-1 ((t (:inherit outline-1 :box nil :height 1.0 :family "Consolas"))))
 '(org-level-2 ((t (:inherit outline-2 :box nil :height 1.0 :family "Consolas"))))
 '(org-level-3 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-level-4 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-level-5 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-level-6 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-level-7 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-level-8 ((t (:inherit default :foreground "#eeeeec"))))
 '(org-priority ((t (:inherit font-lock-keyword-face :height 1.0 :family "Consolas"))))
 '(org-table ((t (:foreground "LightSkyBlue" :height 1.0 :family "Consolas"))))
 '(org-tag ((t (:slant oblique :height 0.7 :family "Consolas" :foreground "#3465a4"))))
 '(org-todo ((t (:foreground "yellow" :weight bold :height 1.0 :family "Consolas"))))
 '(outline-1 ((t (:foreground "SeaGreen1" :weight bold :height 1.0 :family "Consolas"))))
 '(outline-2 ((t (:foreground "SeaGreen1" :weight bold :height 1.0 :family "Consolas"))))
 '(default ((t (:box nil :inherit nil :stipple nil :background "#2e3436" :foreground "#eeeeec" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 170 :width normal :foundry "nil" :family "Consolas"))))
 '(button ((t (:underline t :box (:line-width 2 :color "grey" :style released-button) :foreground "black" :background "grey" :weight bold))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(header-line ((t (:box (:line-width -1 :color "grey20" :style released-button) :background "grey20" :foreground "grey90" :height 0.9))))
 '(shadow ((t (:foreground "grey70"))))
 '(tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(scroll-bar ((t (:background "grey75" :foreground "WhiteSmoke"))))
 '(tooltip ((t (:background "lightyellow" :foreground "black"))))
 '(vertical-border ((t (:background "dim gray"))))
 '(window-divider ((((type graphic)) :foreground "#099709")))
 '(window-divider-first-pixel ((((type graphic)) :foreground "#3cb370")))
 '(window-divider-last-pixel ((((type graphic)) :inherit window-divider-first-pixel)))
 '(alect-prompt ((((type graphic)) :foreground "#dc8cc3" :weight bold)))
 '(alect-time ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-author ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-key ((((type graphic)) :foreground "#fa6a6e" :weight bold)))
 '(alect-selected-item ((((type graphic)) :background "#4f4f4f" :box (:line-width -1 :color "#d5d2be" :style nil))))
 '(alect-color-level-1 ((((type graphic)) :foreground "#00aff5")))
 '(alect-color-level-2 ((((type graphic)) :foreground "#7fb07f")))
 '(alect-color-level-3 ((((type graphic)) :foreground "#db4334")))
 '(alect-color-level-4 ((((type graphic)) :foreground "#abab3a")))
 '(alect-color-level-5 ((((type graphic)) :foreground "#528d8d")))
 '(alect-color-level-6 ((((type graphic)) :foreground "#94bff3")))
 '(alect-color-level-7 ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-color-level-8 ((((type graphic)) :foreground "#fe8b04")))
 '(alect-color-level-9 ((((type graphic)) :foreground "#32cd32")))
 '(alect-color-level-10 ((((type graphic)) :foreground "#fa6a6e")))
 '(alect-color-level-11 ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-color-level-12 ((((type graphic)) :foreground "#be59d8")))
 '(alect-title ((((type graphic)) :foreground "#099709" :weight bold :height 1.13)))
 '(alect-title-1 ((((type graphic)) :inherit alect-color-level-1 :weight bold :height 1.13)))
 '(alect-title-2 ((((type graphic)) :inherit alect-color-level-2 :weight bold :height 1.13)))
 '(alect-title-3 ((((type graphic)) :inherit alect-color-level-3 :weight bold :height 1.13)))
 '(alect-title-4 ((((type graphic)) :inherit alect-color-level-4 :weight bold :height 1.13)))
 '(alect-title-5 ((((type graphic)) :inherit alect-color-level-5 :weight bold :height 1.13)))
 '(alect-title-6 ((((type graphic)) :inherit alect-color-level-6 :weight bold :height 1.13)))
 '(alect-title-7 ((((type graphic)) :inherit alect-color-level-7 :weight bold :height 1.13)))
 '(alect-title-8 ((((type graphic)) :inherit alect-color-level-8 :weight bold :height 1.13)))
 '(alect-button ((((type graphic)) :foreground "#f6f0e1" :background "#6f6f6f" :box (:line-width 2 :style released-button))))
 '(alect-button-pressed ((((type graphic)) :inherit alect-button :box (:line-width 2 :style pressed-button))))
 '(alect-button-mouse ((((type graphic)) :inherit highlight :box (:line-width 2 :style released-button))))
 '(alect-tab-default ((((type graphic)) :height 0.9 :box nil)))
 '(alect-tab-unselected ((((type graphic)) :inherit alect-tab-default :foreground "#8c826d" :background "#4f4f4f" :box (:line-width 1 :style released-button))))
 '(alect-tab-selected ((((type graphic)) :inherit alect-tab-unselected :foreground "#f6f0e1" :background "#5f5f5f")))
 '(alect-tab-mouse ((((type graphic)) :inherit alect-tab-default :inherit mode-line-highlight)))
 '(apropos-keybinding ((((type graphic)) :inherit alect-key)))
 '(apropos-symbol ((((type graphic)) :foreground "#3cb370" :weight bold)))
 '(ac-candidate-face ((((type graphic)) :foreground "#000000" :background "#6f6f6f")))
 '(ac-selection-face ((((type graphic)) :foreground "#3f3f3f" :background "#d5d2be")))
 '(ac-completion-face ((((type graphic)) :foreground "#8c826d")))
 '(ac-candidate-mouse-face ((((type graphic)) :inherit highlight)))
 '(calendar-today ((((type graphic)) :box (:line-width -1 :color "#ea3838" :style nil))))
 '(diary ((t (:foreground "IndianRed"))))
 '(diary-anniversary ((t (:foreground "Cyan1"))))
 '(diary-time ((t (:foreground "LightGoldenrod"))))
 '(holiday ((t (:background "chocolate4"))))
 '(change-log-date ((((type graphic)) :inherit alect-time)))
 '(change-log-name ((((type graphic)) :inherit alect-author)))
 '(change-log-email ((((type graphic)) :foreground "#fa6a6e")))
 '(change-log-file ((((type graphic)) :foreground "#32cd32")))
 '(change-log-list ((((type graphic)) :inherit font-lock-function-name-face)))
 '(change-log-conditionals ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(change-log-function ((((type graphic)) :foreground "#fe8b04")))
 '(change-log-acknowledgment ((((type graphic)) :inherit font-lock-keyword-face)))
 '(comint-highlight-prompt ((t (:foreground "cyan1"))))
 '(comint-highlight-input ((t (:bold t :weight bold))))
 '(company-tooltip ((t (:foreground "#e4e4ef" :background "#282828"))))
 '(company-tooltip-selection ((t (:foreground "#e4e4ef" :background "#101010"))))
 '(company-tooltip-mouse ((t (:background "#101010"))))
 '(company-tooltip-annotation ((t (:foreground "#cc8c3c" :background "#282828"))))
 '(company-tooltip-common ((t (:foreground "#73c936"))))
 '(company-tooltip-common-selection ((t (:foreground "#73c936"))))
 '(company-preview ((t (:background "#73c936"))))
 '(company-preview-common ((t (:foreground "#73c936" :background "#101010"))))
 '(company-scrollbar-fg ((t (:background "#101010"))))
 '(company-scrollbar-bg ((t (:background "#453d41"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(completions-common-part ((t (:width normal :weight normal :slant normal :foreground "WhiteSmoke" :background "black" :height 81))))
 '(ctbl:face-cell-select ((((type graphic)) :background "#62b6ea" :foreground "#3f3f3f")))
 '(ctbl:face-continue-bar ((((type graphic)) :background "#222222" :foreground "#3f3f3f")))
 '(ctbl:face-row-select ((((type graphic)) :background "#1fb3b3" :foreground "#3f3f3f")))
 '(custom-button ((t (:box (:line-width 1 :style released-button) :background "grey50" :foreground "black"))))
 '(custom-button-pressed ((t (:inherit (quote custom-button) :box (:style pressed-button)))))
 '(custom-button-mouse ((t (:inherit (quote custom-button) :background "grey60"))))
 '(custom-button-unraised ((t (:background "grey50" :foreground "black"))))
 '(custom-button-pressed-unraised ((((type graphic)) :inherit custom-button-unraised :underline t)))
 '(custom-documentation ((t (:italic t))))
 '(custom-comment ((((type graphic)) :foreground "#9f9f9f")))
 '(custom-state ((t (:foreground "#73c936"))))
 '(custom-link ((((type graphic)) :inherit link)))
 '(custom-group-tag ((t (:bold t :foreground "#edd400" :height 1.3))))
 '(custom-group-tag-1 ((((type graphic)) :inherit alect-title-2)))
 '(custom-group-subtitle ((((type graphic)) :inherit alect-title-3)))
 '(custom-face-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
 '(custom-variable-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
 '(custom-variable-button ((t (:inherit (quote custom-button)))))
 '(custom-visibility ((((type graphic)) :inherit link :height 0.8)))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "seashell4"))))
 '(diff-added ((t (:foreground "Green"))))
 '(diff-removed ((t (:foreground "salmon1"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "white" :background "darkolivegreen"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "white" :background "dodgerblue4"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "white" :background "indianred4"))))
 '(diff-refine-added ((((type graphic)) :inherit diff-added :underline t)))
 '(diff-refine-removed ((((type graphic)) :inherit diff-removed :underline t)))
 '(diff-header ((((class color) (min-colors 89)) (:background "grey45"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "grey60"))))
 '(diff-function ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-index ((((class color) (min-colors 89)) (:inherit diff-file-header))))
 '(diff-nonexistent ((t (:bold t :weight bold :background "Black" :foreground "Wheat1"))))
 '(dired-directory ((t (:foreground "#96a6c8" :weight bold))))
 '(dired-flagged ((((type graphic)) :foreground "#ea3838")))
 '(dired-header ((((type graphic)) :inherit alect-title)))
 '(dired-ignored ((t (:foreground "#95a99f" :inherit unspecified))))
 '(dired-mark ((((type graphic)) :foreground "#00aff5")))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(dired-perm-write ((((type graphic)) :foreground "#32cd32")))
 '(dired-symlink ((((type graphic)) :inherit font-lock-constant-face)))
 '(dired-warning ((((type graphic)) :inherit font-lock-warning-face :background "#222222")))
 '(eldoc-highlight-function-argument ((t (:bold t :weight bold))))
 '(epa-mark ((t (:bold t :foreground "orange" :weight bold))))
 '(epa-string ((t (:foreground "lightyellow"))))
 '(epa-validity-disabled ((t (:italic t :slant italic))))
 '(epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
 '(epa-validity-low ((t (:italic t :slant italic))))
 '(flymake-errline ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-negation-char-face ((t (:foreground "#6ac214"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#524DFF"))))
 '(gnus-group-news-2-empty ((t (:foreground "#4D58FF"))))
 '(gnus-group-news-3-empty ((t (:foreground "#4D6AFF"))))
 '(gnus-group-news-4-empty ((t (:foreground "#4D7CFF"))))
 '(gnus-group-news-5-empty ((t (:foreground "#4D8EFF"))))
 '(gnus-group-news-6-empty ((t (:foreground "#4DA0FF"))))
 '(gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
 '(gnus-group-news-6 ((t (:bold t :foreground "#80BBFF" :weight bold))))
 '(gnus-group-mail-1-empty ((t (:foreground "#249900"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#389900"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#4D9900"))))
 '(gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
 '(gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
 '(gnus-summary-low-ancient ((t (:italic t :foreground "LightSteelBlue" :slant italic))))
 '(gnus-summary-low-read ((t (:italic t :foreground "LightSlateGray" :slant italic))))
 '(gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
 '(gnus-summary-low-unread ((t (:italic t :foreground "MediumSeaGreen" :slant italic))))
 '(gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
 '(gnus-summary-normal-read ((t (:foreground "grey50"))))
 '(gnus-summary-normal-ticked ((t (:foreground "LightSalmon"))))
 '(gnus-summary-normal-unread ((t (:foreground "YellowGreen"))))
 '(gnus-summary-high-ancient ((t (:bold t :foreground "CornflowerBlue" :weight bold))))
 '(gnus-summary-high-read ((t (:bold t :foreground "grey60" :weight bold))))
 '(gnus-summary-high-ticked ((t (:bold t :foreground "RosyBrown" :weight bold))))
 '(gnus-summary-high-unread ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(gnus-summary-selected ((t (:underline t :foreground "LemonChiffon"))))
 '(helm-header-line-left-margin ((((type graphic)) :inherit alect-prompt)))
 '(helm-header ((t (:background "DeepSkyBlue4" :weight bold))))
 '(helm-source-header ((t (:foreground "#ffdd33" :background "#181818" :box (:line-width -1 :style released-button)))))
 '(helm-separator ((((type graphic)) :foreground "#3390dc")))
 '(helm-selection ((t (:background "#282828" :underline nil))))
 '(helm-selection-line ((t (:background "#282828"))))
 '(helm-visible-mark ((((type graphic)) :foreground "#e8e815")))
 '(helm-candidate-number ((t (:background "#453d41" :foreground "#ffdd33" :bold t))))
 '(helm-grep-file ((((type graphic)) :inherit compilation-info)))
 '(help-argument-name ((t (:italic t :slant italic))))
 '(hl-line ((t (:background "grey10" :foreground "Old Lace"))))
 '(hydra-face-amaranth ((((type graphic)) :foreground "#fe8b04" :weight bold)))
 '(hydra-face-red ((((type graphic)) :foreground "#fa5151" :weight bold)))
 '(hydra-face-pink ((((type graphic)) :foreground "#ebabde" :weight bold)))
 '(hydra-face-blue ((((type graphic)) :foreground "#94bff3" :weight bold)))
 '(hydra-face-teal ((((type graphic)) :foreground "#528d8d" :weight bold)))
 '(info-title-1 ((((type graphic)) :inherit alect-color-level-1 :height 1.5 :weight bold)))
 '(info-title-2 ((((type graphic)) :inherit alect-color-level-2 :height 1.4 :weight bold)))
 '(info-title-3 ((((type graphic)) :inherit alect-color-level-3 :height 1.3 :weight bold)))
 '(info-title-4 ((((type graphic)) :inherit alect-color-level-4 :height 1.2 :weight bold)))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-menu-star ((((type graphic)) :foreground "#ea3838")))
 '(Info-quoted ((((type graphic)) :foreground "#f6f0e1" :weight bold)))
 '(ido-first-match ((((class color) (min-colors 89)) (:weight normal :foreground "orange"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "green"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-keyword-face))))
 '(ido-virtual ((((type graphic)) :foreground "#fa6a6e")))
 '(isearch-fail ((t (:background "red4"))))
 '(linum ((t (\` (list :foreground gruber-darker-quartz :background gruber-darker-bg)))))
 '(magit-dimmed ((((type graphic)) :inherit shadow)))
 '(magit-section-heading ((((type graphic)) :inherit alect-title)))
 '(magit-section-highlight ((((type graphic)) :background "#4f4f4f")))
 '(magit-section-heading-selection ((((type graphic)) :foreground "#b2c3f8")))
 '(magit-head ((((type graphic)) :background "#222222" :foreground "#f6f0e1" :box (:line-width 2 :color "#ea3838"))))
 '(magit-refname ((((type graphic)) :box (:line-width 1 :color "#d5d2be"))))
 '(magit-refname-wip ((((type graphic)) :inherit magit-refname :foreground "#fa5151")))
 '(magit-refname-stash ((((type graphic)) :inherit magit-refname :foreground "#dc8cc3")))
 '(magit-branch-local ((((type graphic)) :inherit magit-refname :foreground "#62b6ea")))
 '(magit-branch-current ((((type graphic)) :inherit magit-branch-local :box (:line-width 2 :color "#ea3838"))))
 '(magit-branch-remote ((((type graphic)) :inherit magit-refname :foreground "#3cb370")))
 '(magit-tag ((t (:foreground "#ffdd33" :background "#181818"))))
 '(magit-hash ((((type graphic)) :foreground "#abab3a")))
 '(magit-log-date ((((type graphic)) :inherit alect-time)))
 '(magit-log-author ((t (:foreground "#cc8c3c"))))
 '(magit-reflog-checkout ((((type graphic)) :inherit magit-branch-local)))
 '(magit-reflog-remote ((((type graphic)) :inherit magit-branch-remote)))
 '(magit-reflog-commit ((((type graphic)) :foreground "#32cd32")))
 '(magit-reflog-amend ((((type graphic)) :foreground "#e353b9")))
 '(magit-reflog-merge ((((type graphic)) :foreground "#b2c3f8" :weight bold)))
 '(magit-reflog-reset ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(magit-reflog-rebase ((((type graphic)) :foreground "#fe8b04")))
 '(magit-reflog-cherry-pick ((((type graphic)) :foreground "#1fb3b3")))
 '(magit-reflog-other ((((type graphic)) :inherit magit-branch-local :foreground "#d5d2be")))
 '(magit-bisect-bad ((((type graphic)) :foreground "#db4334" :box (:line-width -1))))
 '(magit-bisect-skip ((((type graphic)) :inherit magit-bisect-bad :foreground "#e5c900")))
 '(magit-bisect-good ((((type graphic)) :inherit magit-bisect-bad :foreground "#3cb370")))
 '(magit-cherry-unmatched ((((type graphic)) :foreground "#c83029")))
 '(magit-cherry-equivalent ((((type graphic)) :foreground "#0c8782")))
 '(magit-process-ok ((((type graphic)) :inherit magit-section-title :foreground "#7fb07f")))
 '(magit-process-ng ((((type graphic)) :inherit magit-section-title :foreground "#ea3838")))
 '(magit-blame-heading ((t (:background "#282828" :foreground "#e4e4ef"))))
 '(magit-blame-summary ((((type graphic)) :inherit magit-blame-heading)))
 '(magit-blame-hash ((((type graphic)) :inherit (magit-hash magit-blame-heading))))
 '(magit-blame-name ((((type graphic)) :inherit (magit-log-author magit-blame-heading))))
 '(magit-blame-date ((((type graphic)) :inherit (magit-log-date magit-blame-heading))))
 '(magit-diff-file-heading ((((type graphic)) :inherit diff-file-header)))
 '(magit-diff-file-heading-selection ((((type graphic)) :inherit (magit-section-heading-selection magit-diff-file-heading-highlight))))
 '(magit-diff-lines-heading ((((type graphic)) :foreground "#3f3f3f" :background "#b2c3f8")))
 '(magit-diff-conflict-heading ((((type graphic)) :inherit magit-diff-hunk-heading :foreground "#c83029")))
 '(magit-diff-hunk-heading ((((type graphic)) :inherit diff-hunk-header)))
 '(magit-diff-hunk-heading-highlight ((((type graphic)) :inherit magit-diff-hunk-heading :background "#222222")))
 '(magit-diff-hunk-heading-selection ((((type graphic)) :inherit (magit-section-heading-selection magit-diff-hunk-heading-highlight))))
 '(magit-diff-context ((((type graphic)) :foreground "#8c826d")))
 '(magit-diff-context-highlight ((((type graphic)) :inherit magit-section-highlight)))
 '(magit-diff-added ((((type graphic)) :inherit diff-added)))
 '(magit-diff-added-highlight ((((type graphic)) :inherit (magit-diff-added magit-diff-context-highlight))))
 '(magit-diff-removed ((((type graphic)) :inherit diff-removed)))
 '(magit-diff-removed-highlight ((((type graphic)) :inherit (magit-diff-removed magit-diff-context-highlight))))
 '(magit-diffstat-added ((((type graphic)) :inherit magit-diff-added)))
 '(magit-diffstat-removed ((((type graphic)) :inherit magit-diff-removed)))
 '(magit-popup-heading ((((type graphic)) :inherit alect-title)))
 '(magit-popup-key ((((type graphic)) :inherit alect-key)))
 '(magit-popup-argument ((((type graphic)) :foreground "#b2c3f8" :weight bold)))
 '(magit-popup-disabled-argument ((((type graphic)) :foreground "#9f9f9f")))
 '(magit-sequence-pick ((((type graphic)) :underline (:color "#8c826d"))))
 '(magit-sequence-part ((((type graphic)) :inherit magit-sequence-pick :foreground "#e5c900")))
 '(magit-sequence-head ((((type graphic)) :inherit magit-sequence-pick :foreground "#94bff3")))
 '(magit-sequence-drop ((((type graphic)) :inherit magit-sequence-pick :foreground "#db4334")))
 '(magit-sequence-onto ((((type graphic)) :inherit magit-sequence-pick :foreground "#e81eda")))
 '(magit-sequence-stop ((((type graphic)) :inherit magit-sequence-pick :foreground "#528d8d")))
 '(magit-sequence-done ((((type graphic)) :inherit magit-sequence-pick :foreground "#3390dc")))
 '(magit-signature-good ((((type graphic)) :foreground "#32cd32")))
 '(magit-signature-bad ((((type graphic)) :foreground "#fa5151")))
 '(magit-signature-untrusted ((((type graphic)) :foreground "#2fdbde")))
 '(git-commit-summary ((((type graphic)) :weight bold)))
 '(git-commit-comment-branch ((((type graphic)) :foreground "#62b6ea")))
 '(git-commit-comment-file ((((type graphic)) :inherit default)))
 '(git-commit-comment-heading ((((type graphic)) :inherit alect-title)))
 '(git-commit-comment-action ((((type graphic)) :foreground "#e5c900")))
 '(markdown-header-face ((((type graphic)) :inherit alect-title-1)))
 '(markdown-header-face-1 ((((type graphic)) :inherit alect-title-1)))
 '(markdown-header-face-2 ((((type graphic)) :inherit alect-title-2)))
 '(markdown-header-face-3 ((((type graphic)) :inherit alect-title-3)))
 '(markdown-header-face-4 ((((type graphic)) :inherit alect-title-4)))
 '(markdown-header-face-5 ((((type graphic)) :inherit alect-title-5)))
 '(markdown-header-face-6 ((((type graphic)) :inherit alect-title-6)))
 '(markdown-header-rule-face ((((type graphic)) :inherit markdown-header-face :foreground "#f0dfaf")))
 '(markdown-header-delimiter-face ((((type graphic)) :inherit markdown-header-face :foreground "#f6f0e1")))
 '(markdown-footnote-face ((((type graphic)) :foreground "#3390dc")))
 '(markdown-inline-code-face ((((type graphic)) :foreground "#528d8d")))
 '(markdown-comment-face ((((type graphic)) :inherit font-lock-comment-face)))
 '(markdown-blockquote-face ((((type graphic)) :inherit font-lock-doc-face)))
 '(markdown-bold-face ((((type graphic)) :inherit bold)))
 '(markdown-italic-face ((((type graphic)) :inherit italic)))
 '(markdown-missing-link-face ((((type graphic)) :inherit font-lock-warning-face)))
 '(markdown-link-face ((((type graphic)) :inherit link)))
 '(markdown-link-title-face ((((type graphic)) :inherit font-lock-string-face)))
 '(markdown-url-face ((((type graphic)) :foreground "#099709")))
 '(markdown-language-keyword-face ((((type graphic)) :foreground "#be59d8")))
 '(markdown-line-break-face ((((type graphic)) :inherit underline)))
 '(markdown-list-face ((((type graphic)) :foreground "#f6f0e1" :weight bold)))
 '(markdown-metadata-key-face ((((type graphic)) :foreground "#b2c3f8")))
 '(markdown-metadata-value-face ((((type graphic)) :foreground "#fa5151")))
 '(markdown-pre-face ((((type graphic)) :foreground "#abab3a")))
 '(markdown-reference-face ((((type graphic)) :inherit link)))
 '(message-header-newsgroups ((t (:italic t :bold t :foreground "papaya whip" :slant italic :weight bold))))
 '(message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
 '(message-mml ((t (:foreground "MediumSpringGreen"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button :height 0.9)))))
 '(org-agenda-date ((t (:foreground "LightSkyBlue"))))
 '(org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
 '(org-agenda-structure ((t (:foreground "LightSkyBlue"))))
 '(org-archived ((t (:foreground "grey70"))))
 '(org-date ((t (:foreground "Cyan" :underline t))))
 '(org-date-selected ((((type graphic)) :inherit alect-selected-item)))
 '(org-document-info ((((type graphic)) :foreground "#fa5151")))
 '(org-document-info-keyword ((((type graphic)) :foreground "#e5c900")))
 '(org-formula ((t (:foreground "chocolate1"))))
 '(org-hide ((t (:foreground "black"))))
 '(org-link ((t (:foreground "Cyan" :underline t))))
 '(org-mode-line-clock ((t (:foreground "DarkGreen" :underline t))))
 '(org-mode-line-clock-overrun ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(org-scheduled ((((type graphic)) :foreground "#8ce096")))
 '(org-scheduled-previously ((t (:foreground "chocolate1"))))
 '(org-scheduled-today ((t (:foreground "PaleGreen"))))
 '(org-special-keyword ((t (:foreground "LightSalmon"))))
 '(org-time-grid ((t (:foreground "LightGoldenrod"))))
 '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
 '(org-verbatim ((t (:foreground "grey70" :underline t))))
 '(org-warning ((t (:bold t :weight bold :foreground "Pink"))))
 '(org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(outline-6 ((t (:foreground "Aquamarine"))))
 '(outline-7 ((t (:foreground "LightSteelBlue"))))
 '(outline-8 ((t (:foreground "LightSalmon"))))
 '(popup-tip-face ((((type graphic)) :foreground "#000000" :background "#f8ffa0")))
 '(popup-scroll-bar-foreground-face ((((type graphic)) :background "#8c826d")))
 '(popup-scroll-bar-background-face ((((type graphic)) :background "#222222")))
 '(popup-isearch-match ((((type graphic)) :foreground "#d5d2be" :background "#3f3f3f")))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(show-paren-match ((t (:background "steelblue3"))))
 '(speedbar-file-face ((t (:foreground "cyan"))))
 '(speedbar-directory-face ((t (:foreground "light blue"))))
 '(speedbar-tag-face ((t (:foreground "yellow"))))
 '(speedbar-selected-face ((t (:foreground "red" :underline t))))
 '(speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
 '(speedbar-highlight-face ((t (:background "sea green"))))
 '(speedbar-button-face ((t (:foreground "green3"))))
 '(vc-up-to-date-state ((((type graphic)) :foreground "#32cd32")))
 '(vc-edited-state ((((type graphic)) :foreground "#e5c900")))
 '(vc-missing-state ((((type graphic)) :foreground "#ea3838")))
 '(vc-conflict-state ((((type graphic)) :foreground "#c83029" :weight bold)))
 '(vc-locked-state ((((type graphic)) :foreground "#2fdbde")))
 '(vc-locally-added-state ((((type graphic)) :foreground "#62b6ea")))
 '(vc-needs-update-state ((((type graphic)) :foreground "#e353b9")))
 '(vc-removed-state ((((type graphic)) :foreground "#fa5151")))
 '(which-func ((t (:foreground "Blue1"))))
 '(widget-field ((t (:background "dim gray"))))
 '(widget-button ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(widget-button-pressed ((t (:foreground "red1" :background "lightgrey" :box (:line-width 2 :style pressed-button)))))
 '(widget-documentation ((t (:foreground "lime green"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "dim gray"))))
 '(fixed-pitch ((t (:inherit (default)))))
 '(mode-line-emphasis ((t (:bold t :weight bold))))
 '(next-error ((t (:background "blue3"))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-xref-visited ((t (:foreground "#ad7fa8"))))
 '(org-quote ((t (:inherit org-block :slant italic))))
 '(org-verse ((t (:inherit org-block :slant italic))))
 '(org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
 '(aw-leading-char-face ((t (:background "gray30" :foreground "red" :weight bold))))
 '(icomplete-first-match ((t (:foreground "deep sky blue" :weight bold))))
 '(ivy-current-match ((t (:inherit highlight))))
 '(ivy-minibuffer-match-face-1 ((t (:background "gray50" :weight normal))))
 '(ivy-minibuffer-match-face-2 ((t (:background "gold3" :weight bold))))
 '(ivy-minibuffer-match-face-4 ((t (:background "forest green" :weight bold))))
 '(ivy-remote ((t (:foreground "deep sky blue" :slant italic))))
 '(org-agenda-done ((t (:foreground "#269926"))))
 '(org-agenda-restriction-lock ((t (:background "skyblue4"))))
 '(org-drawer ((t (:foreground "LightSkyBlue"))))
 '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
 '(border ((t (:background "gold" :foreground "black"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#cc8c3c" :background "#101010"))))
 '(gnus-splash ((t (:foreground "#cccccc"))))
 '(gnus-summary-high-undownloaded ((t (:bold t :foreground "ivory3" :weight bold))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
 '(gnus-summary-low-undownloaded ((t (:italic t :foreground "grey75" :slant italic :weight normal))))
 '(org-code ((t (:foreground "grey70"))))
 '(org-sexp-date ((t (:foreground "Cyan"))))
 '(org-target ((t (:underline t))))
 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:bold t :italic t :slant italic :weight bold))))
 '(buffer-menu-buffer ((t (:bold t :weight bold))))
 '(completions-first-difference ((t (:bold t :weight bold))))
 '(diary-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
 '(eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
 '(epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
 '(epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(file-name-shadow ((t (:foreground "grey70"))))
 '(ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Pink"))))
 '(ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
 '(italic ((t (:italic t))))
 '(mouse ((t (:background "OrangeRed"))))
 '(nobreak-space ((t (:foreground "cyan" :underline t))))
 '(smerge-base ((t (:foreground "orange"))))
 '(smerge-markers ((t (:background "grey30"))))
 '(smerge-upper ((t (:foreground "cyan"))))
 '(smerge-lower ((t (:foreground "lightgreen"))))
 '(table-cell ((t (:background "blue1" :foreground "gray90"))))
 '(underline ((t (:underline t))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2")))))

(provide-theme 'RyanTheme)
