; fileextensions.el

(add-to-list 'auto-mode-alist	'("\\.org$|\\.org.gpg$|\\.org.gpg_archive$|\\.org_archive$|\\.org\\|\\.txt$" . org-mode))
(add-to-list 'auto-mode-alist '("\\.[JW]AR\\|\\.[jw]ar\\|\\.egg\\" . archive-mode))
(add-to-list 'auto-mode-alist '("\\.[sj]?html?\\|\\.phtml\\|\\.rhtml\\|\\.erb\\|\\.inc\\|\\.jsp\\|\\.php[34]?\\'|\\.php\\'|wp-content/themes/.*/.*\\.php\\'"  . html-mode))
(add-to-list 'auto-mode-alist '("\\.\\(p\\(?:k[bg]\\|ls\\)\\|sql\\)\\'|\\.pld$\\|\\.pls$\\|\\.pld$" . plsql-mode))
(add-to-list 'auto-mode-alist '("\\.arc\\|\\.asd\\|\\.lisp-expr\\'" . lisp-mode))
(add-to-list 'auto-mode-alist '("\\.cs\\'" . java-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'|\\.scss\\'" . css-mode))
(add-to-list 'auto-mode-alist '("\\.doc\\'" . no-word))
(add-to-list 'auto-mode-alist '("\\.elc\\'" . emacs-lisp-mode))
(add-to-list 'auto-mode-alist '("\\.java\\'" . jde-mode))
(add-to-list 'auto-mode-alist '("\\.js$|\\.js\\'\\|\\.json\\'|\\.[ja]s\\'|\\.htc\\'|\\.json\\'" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.mw$" . mediawiki-mode))
(add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-tools-install))
(add-to-list 'auto-mode-alist '("\\.psql\\|\\.view\\'|\\.sql\\'|.sqlite\\'|\\.db$\\" . sql-mode))
(add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
(add-to-list 'auto-mode-alist '("\\.SCORE\\'" . gnus-score-mode))
(add-to-list 'auto-mode-alist '("\\.tex\\'" . latex-mode))
(add-to-list 'auto-mode-alist '("\\.wiki\\'" . wikipedia-mode)))
(add-to-list 'auto-mode-alist '("\\Gemfile\\'|\\Rakefile\\'|\\Capfile\\'|\\.rake\\'|\\.rb\\" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\todo.txt\\'" . todotxt-mode))